# Generated by Django 4.1.2 on 2022-10-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
