# Generated by Django 4.1.2 on 2022-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_rename_materials_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('master', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('date_time', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
