# Generated by Django 4.1.2 on 2022-10-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Services',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty.person'),
        ),
    ]
