# Generated by Django 4.1.2 on 2022-10-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_rename_work_services_alter_order_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='clientID',
        ),
        migrations.AddField(
            model_name='order',
            name='ServicesID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty.services'),
            preserve_default=False,
        ),
    ]
