# Generated by Django 4.1.2 on 2022-10-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_rename_client_order_clientid_order_servicesid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clientID',
            new_name='personID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ServicesID',
            new_name='servicesID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
