# Generated by Django 4.1.2 on 2022-10-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0008_rename_clientid_order_personid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPerson',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=89058614934, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='id_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beauty.categoryperson'),
            preserve_default=False,
        ),
    ]
