# Generated by Django 4.1.2 on 2022-10-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0009_categoryperson_person_mail_person_phone_person_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_category',
        ),
    ]
