# Generated by Django 4.1.2 on 2022-10-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_remove_person_id_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryPerson',
        ),
    ]
