# Generated by Django 4.1.2 on 2022-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0012_categoryperson_person_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
