# Generated by Django 4.1.2 on 2022-10-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0014_remove_order_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beauty.categoryperson'),
        ),
    ]
