# Generated by Django 4.1.2 on 2022-10-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0016_rename_personid_order_uuid_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uuid_person',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uuid_services',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_category',
        ),
        migrations.DeleteModel(
            name='CategoryPerson',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
