# Generated by Django 4.1.2 on 2022-10-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beauty', '0017_delete_material_remove_order_uuid_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPerson',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('mail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255, verbose_name='Пол')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beauty.categoryperson')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('profit', models.IntegerField()),
                ('uuid_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty.person')),
                ('uuid_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty.services')),
            ],
        ),
    ]
