# Generated by Django 4.1.2 on 2022-10-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_uuid_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.material')),
                ('uuid_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='uuid_materials',
            field=models.ManyToManyField(through='core.Membership', to='core.material'),
        ),
    ]
