# Generated by Django 4.1.2 on 2022-10-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membership_order_uuid_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.person'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.services'),
        ),
    ]
